#!/bin/bash
#
# Program 1 -- CS 344, Fall 2016
# C
# Calculates mean and median of each row or column in a table of values
#
# Tim Thomas


# Setup temperorary files needed
TMP_stdin=temp$$_stdin
TMP_transpose=temp$$_transpose
TMP_median=temp$$_median

# trap interrupt, hangup and terminate signals; cleanup temp files
# if signals caught
trap "rm -f temp$$*; exit 1" INT HUP TERM


usage='Usage: stats {-rows|-cols} [file]'


# This function calculates the average (mean) of a row of values.
# $1 is a row of whitespace-separated values
function calc_average {

    # Calculate sum of row or col and # of values in row or col
    sum=0
    cnt=0
    for val in $1; do
        sum=`expr $sum + $val`
        cnt=`expr $cnt + 1`
    done

    #
    # calculate mean (sum/cnt). Half rounds up per assignment spec.
    #

    # if divisor is even:
    if [ $((cnt % 2)) -eq 0 ]; then                 
        if [ $((sum % cnt)) -ge $((cnt/2)) ]; then  # round up 
            mean=`expr $sum / $cnt + 1`
        else                                        # round down
            mean=`expr $sum / $cnt`
        fi

    # otherwise, divisor is odd
    else                                           
        if [ $((sum % cnt)) -gt $((cnt/2)) ]; then  # round up 
            mean=`expr $sum / $cnt + 1`
        else                                        # round down
            mean=`expr $sum / $cnt`
        fi
    fi

    echo $mean
}


# This function calculates the median of a row of values.
# $1 is a row of whitespace-separated values
function calc_median {

    # determine how many values we have
    cnt=0
    for val in $1; do
        cnt=`expr $cnt + 1`
        echo $val >> $TMP_median
    done

    # find location of middle value (bias towards greater value if cnt is even)
    middle=`expr $cnt / 2 + 1`

    # calculate median: 
    #    list values | sort by number | list first $middle rows | list last row
    median=`cat $TMP_median | sort -n | head -${middle} | tail -1`

    rm -f $TMP_median
    echo $median
}


# This function converts rows of values to columns of values.
# Transposed data saved to file $TMP_transpose.
# $1 contains input data to be transposed.
function transpose {

    # Get number of columns
    numCols=0
    read line <$1
    for val in ${line}; do
        numCols=`expr $numCols + 1`
    done

    # transpose data 
    i=1
    while [[ $i -le $numCols ]] ; do 

        # extract each column, convert to a row by swapping newlines with tabs
        cut -f $i $1 | tr '\n' '\t' >> $TMP_transpose
        echo "" >> $TMP_transpose
        i=`expr $i + 1` 
    done
}


#  
#  Check Command Line Usage
# 

#  check that number of args is 2 or 1
if [[ $# -eq 2 ]]; then   

    #   check that optional second arg is a file and is readable
    if [ ! -r $2 ]; then
        echo "$2 is not a readable file." >&2
        exit 1
    fi

    #   check that input file has length greater than zero 
    if [ ! -s $2 ]; then
        echo "$2 is empty." >&2
        exit 1
    fi

    input=$2

# no input file provided, so process data from stdin
elif [[ $# -eq 1 ]]; then
    cat > $TMP_stdin
    input=$TMP_stdin

# error, incorrect # of command line args
else
    echo $usage >&2
    exit 1
fi


#
#  Loop through rows/columns and perform calculations
#

# First make sure first arg starts with 'r' or 'c'
#
# Processing rows
if [[ $1 == -r* ]]; then      
    echo Average Median

    # Calculate/print average and median for each row
    while read line; do

        avg=$(calc_average "${line}")
        median=$(calc_median "${line}")

        echo -e "$avg       $median"

    done < ${input}

# processing columns
elif [[ $1 == -c* ]]; then   

    # The functions written at the top of this script handle rows of data.  
    # So we modify input data so that rows/cols are transposed.
    # And then we can process in the same way as if the user had passed -r.
    transpose $input
    input=$TMP_transpose

    # Loop through each column (now as rows); calc and print averages
    echo "Averages:"
    while read line; do
        avg=$(calc_average "${line}")
        echo -ne "$avg      "
    done <$input

    # Loop through each column (now as rows); calc and print medians
    echo -e "\nMedians:"
    while read line; do

        median=$(calc_median "${line}")
        echo -ne $median'      '

    done < ${input}

# error, first argument must start with -r or -c
else
    echo $usage >&2
    exit 1
fi

echo ""   # need a newline at very end

# cleanup temp files
rm -f temp$$*
